### ISSUE TITLE
Could Chevrotain be relevant as the underlying engine?

### ISSUE THREAD

**Issue by bd82** [blainehansen/kreia#1]
See: 
* [Description](https://tomassetti.me/parsing-in-javascript/#chevrotain).
* [Guide](http://sap.github.io/chevrotain/docs/guide/custom_apis.html) for custom APIs.
* [Benchmark](https://sap.github.io/chevrotain/performance/).

### Pros
* Very Very fast.
* Fancy Parser features such as error recovery, automatic syntax tree creation, syntax diagrams creation.
* Fancy Lexer features such as Token categories, Token ignoring, Token Grouping, custom Token patterns...

### Cons
* No embedded actions support (yet). so must use a CST(Parser Tree) visitor post parsing.
* Requires code generation (or eval).

**Comment by blainehansen** [comment]
I thought about using Chevrotain actually. But after thinking about it, I decided that embedded actions and an incredibly clear api were the absolute main priorities. I felt Chevrotain's many features would cause distractions from those main goals and I wanted everything to be laser focused.

Thank you for reaching out though!

**Comment by bd82** [comment]
👍
